---
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - caskroom/versions
    brew_packages:
    - bash
    - bash-completion
    - coreutils
    - ctags
    - findutils
    - git
    - git-crypt
    - gpg
    - lesspipe
    - mackup
    - node
    - rbenv
    - ruby-build
    - ssh-copy-id
    - svn
    - the_silver_searcher
    - tmux
    - tree
    - vim
    - watch
    - wget
    - zsh
    - homebrew/php/composer
    cask_packages:
    - airfoil # not working
    - alfred2
    - android-file-transfer
    - android-studio
    - battle-net
    - bettertouchtool
    - betterzipql
    - chrome-remote-desktop-host
    - coccinellida
    - cloudup
    - cyberduck
    - discord
    - disk-inventory-x
    - divvy
    - dropbox
    - firefox
    - google-chrome
    - google-hangouts
    - hyperdock
    - iterm2
    - java
    - karabiner
    - mailplane
    - mou
    - mumble
    - origin
    - plex-home-theater
    - poedit
    - private-internet-access
    - qlimagesize
    - qlmarkdown
    - qlprettypatch
    - rowanj-gitx
    - resilio-sync
    - sequel-pro
    - skype
    - slack
    - spotify
    - steam
    - sublime-text
    - suspicious-package
    - synergy
    - taskpaper
    - textmate
    - transmit
    - unified-remote
    - vagrant
    - versions
    - virtualbox
    - vlc
    - vmware-fusion
    - xtrafinder